/*
	Author name: Harsha Tolani
	Date: 14/8/2022
	Description :In this we make Custom Controller for contact page
*/


public class contactDetailWithAddRow{
    
    public Map<Integer, Contact> conRecordsMap{get;set;}
    public contactDetailWithAddRow(){
    	conRecordsMap = new Map<Integer, Contact>();
        List<Contact> conRecords = new List<Contact>();
    }
    public void Add(){
        
    }

}